COURT_LABELS = {
    'cmm':            'Chief Metropolitan Magistrate Court Complex, Bangalore',
    'mmtc':           'Metropolitan Magistrate Traffic Courts, Bangalore',
    'mmtc_mayo':      'Metropolitan Magistrate Traffic Court I, Mayo Hall, Bangalore',
    'city_civil':     'City Civil Court Complex, Bangalore',
    'family':         'Family Court Complex, Bangalore',
    'small_causes':   'Small Causes Court Complex, Bangalore',
    'mayo_hall':      'Mayo Hall Court Complex, Bangalore',
    'commercial':     'Commercial Court Complex, Bangalore',
    'consumer':       'Consumer Forum, Shantinagar',
    'urban_consumer': 'Urban Consumer Forum, Bangalore',
    'city_civil_rural':       'City Civil Court Complex, Bengaluru Rural',
    'dist_session_rural':     'PRL. District and Sessions Judge, Bengaluru Rural',
    'prl_senior_rural':       'PRL. Senior Civil Judge, Bengaluru Rural',
    'prl_junior_rural':       'PRL. Civil Judge, Bengaluru Rural',
    'cjm_cmm_rural':          'Chief Judicial Magistrate, Bengaluru Rural in CMM Court',
    'vacation_court_rural':   'Vacation Court, Bengaluru Rural',
    'commercial_court_rural': 'Commercial Court Complex, Bengaluru Rural',
    'labour_court_rural':     'Labour Court, Bengaluru Rural',
    'senior_anekal':          'Senior Civil Judge & JMFC, Anekal',
    'junior_anekal':          'PRL. Civil Judge & JMFC, Anekal',
    'hosakote':               'Court Complex – Hosakote',
    'devanahalli':            'Court Complex – Devanahalli',
    'doddaballapur':          'Court Complex – Doddaballapur',
    'nelamangala':            'Court Complex – Nelamangala',
    'kr_puram':               'KR Puram Court Complex',
    'high_court_karnataka': 'High Court of Karnataka, Bengaluru',
    'supreme_court_india':  'Supreme Court of India, New Delhi',
}

COURT_TO_BUILDING = {
    'city_civil':           'city_civil_complex',
    'small_causes':         'city_civil_complex',
    'city_civil_rural':     'city_civil_complex',
    'dist_session_rural':   'city_civil_complex',
    'prl_senior_rural':     'city_civil_complex',
    'prl_junior_rural':     'city_civil_complex',
    'cmm':                  'magistrates_complex',
    'mmtc':                 'magistrates_complex',
    'mmtc_mayo':            'magistrates_complex',
    'cjm_cmm_rural':        'magistrates_complex',
    'vacation_court_rural': 'magistrates_complex',
    'family':               'family_court',
    'consumer':             'consumer_court',
    'urban_consumer':       'consumer_court',
    'commercial':           'commercial_court',
    'commercial_court_rural': 'commercial_court',
    'mayo_hall':            'mayo_hall',
    'labour_court_rural':   'labour_court',
    'senior_anekal':        'anekal',
    'junior_anekal':        'anekal',
    'hosakote':             'hosakote',
    'devanahalli':          'devanahalli',
    'doddaballapur':        'doddaballapur',
    'nelamangala':          'nelamangala',
    'kr_puram':             'kr_puram',
    'high_court_karnataka': 'high_court',
    'supreme_court_india':  'supreme_court',
}

BUILDING_LABELS = {
    'city_civil_complex': 'City Civil Court Complex',
    'magistrates_complex': 'Magistrates Court Complex',
    'family_court': 'Family Court Complex',
    'consumer_court': 'Consumer Court Complex',
    'commercial_court': 'Commercial Court Complex',
    'mayo_hall': 'Mayo Hall',
    'labour_court': 'Labour Court',
    'anekal': 'Anekal',
    'hosakote': 'Hosakote',
    'devanahalli': 'Devanahalli',
    'doddaballapur': 'Doddaballapur',
    'nelamangala': 'Nelamangala',
    'kr_puram': 'KR Puram',
    'high_court': 'High Court of Karnataka, Bengaluru',
    'supreme_court': 'Supreme Court of India, New Delhi',
}

BUILDING_ORDER = [
    'city_civil_complex',
    'magistrates_complex',
    'family_court',
    'consumer_court',
    'commercial_court',
    'mayo_hall',
    'labour_court',
    'anekal',
    'hosakote',
    'devanahalli',
    'doddaballapur',
    'nelamangala',
    'kr_puram',
    'high_court',
    'supreme_court',
]
