COURT_LABELS = {
    'cmm':            'Chief Metropolitan Magistrate Court Complex, Bangalore',
    'mmtc':           'Metropolitan Magistrate Traffic Courts, Bangalore',
    'mmtc_mayo':      'Metropolitan Magistrate Traffic Court I, Mayo Hall, Bangalore',
    'city_civil':     'City Civil Court Complex, Bangalore',
    'family':         'Family Court Complex, Bangalore',
    'small_causes':   'Small Causes Court Complex, Bangalore',
    'mayo_hall':      'Mayo Hall Court Complex, Bangalore',
    'commercial':     'Commercial Court Complex, Bangalore',
    'consumer':       'Consumer Forum, Shantinagar',
    'urban_consumer': 'Urban Consumer Forum, Bangalore',
    'city_civil_rural':       'City Civil Court Complex, Bengaluru Rural',
    'dist_session_rural':     'PRL. District and Sessions Judge, Bengaluru Rural',
    'prl_senior_rural':       'PRL. Senior Civil Judge, Bengaluru Rural',
    'prl_junior_rural':       'PRL. Civil Judge, Bengaluru Rural',
    'cjm_cmm_rural':          'Chief Judicial Magistrate, Bengaluru Rural in CMM Court',
    'vacation_court_rural':   'Vacation Court, Bengaluru Rural',
    'commercial_court_rural': 'Commercial Court Complex, Bengaluru Rural',
    'labour_court_rural':     'Labour Court, Bengaluru Rural',
    'senior_anekal':          'Senior Civil Judge & JMFC, Anekal',
    'junior_anekal':          'PRL. Civil Judge & JMFC, Anekal',
    'hosakote':               'Court Complex – Hosakote',
    'devanahalli':            'Court Complex – Devanahalli',
    'doddaballapur':          'Court Complex – Doddaballapur',
    'nelamangala':            'Court Complex – Nelamangala',
    'kr_puram':               'KR Puram Court Complex',
    'high_court_karnataka': 'High Court of Karnataka, Bengaluru',
    'supreme_court_india':  'Supreme Court of India, New Delhi',
}
