COURT_LABELS = {
    'cmm':            'Chief Metropolitan Magistrate Court Complex, Bangalore',
    'mmtc':           'Metropolitan Magistrate Traffic Courts, Bangalore',
    'mmtc_mayo':      'Metropolitan Magistrate Traffic Court I, Mayo Hall, Bangalore',
    'city_civil':     'City Civil Court Complex, Bangalore',
    'family':         'Family Court Complex, Bangalore',
    'small_causes':   'Small Causes Court Complex, Bangalore',
    'mayo_hall':      'Mayo Hall Court Complex, Bangalore',
    'commercial':     'Commercial Court Complex, Bangalore',
    'consumer':       'Consumer Forum, Shantinagar',
    'urban_consumer': 'Urban Consumer Forum, Bangalore',
    'state_consumer_basava': 'State Consumer, Basava Bhavan',
    'dc_kandaya':     'DC Court, Kandaya Bhavan',
    'ac_kandaya':     'AC Court, Kandaya Bhavan',
    'mandya_district':      'District Court Complex, Mandya',
    'mandya_maddur':        'Court Complex, Maddur',
    'mandya_malavalli':     'Court Complex, Malavalli',
    'mandya_srirangapatna': 'Court Complex, Srirangapatna',
    'mandya_nagamangala':   'Court Complex, Nagamangala',
    'mandya_pandavapura':   'Court Complex, Pandavapura',
    'mandya_krishnarajapet':'Court Complex, Krishnarajapet',
    'city_civil_rural':       'City Civil Court Complex, Bengaluru Rural',
    'dist_session_rural':     'PRL. District and Sessions Judge, Bengaluru Rural',
    'prl_senior_rural':       'PRL. Senior Civil Judge, Bengaluru Rural',
    'prl_junior_rural':       'PRL. Civil Judge, Bengaluru Rural',
    'cjm_cmm_rural':          'Chief Judicial Magistrate, Bengaluru Rural in CMM Court',
    'vacation_court_rural':   'Vacation Court, Bengaluru Rural',
    'vacation_bench_family':  'Vacation Bench, Family Court, Bangalore',
    'commercial_court_rural': 'Commercial Court Complex, Bengaluru Rural',
    'labour_court_rural':     'Labour Court, Bengaluru Rural',
    'labour_court_urban':     'Labour Court, Bangalore',
    'senior_anekal':          'Senior Civil Judge & JMFC, Anekal',
    'junior_anekal':          'PRL. Civil Judge & JMFC, Anekal',
    'hosakote':               'Court Complex – Hosakote',
    'devanahalli':            'Court Complex – Devanahalli',
    'doddaballapur':          'Court Complex – Doddaballapur',
    'nelamangala':            'Court Complex – Nelamangala',
    'kr_puram':               'KR Puram Court Complex',
    'high_court_karnataka': 'High Court of Karnataka, Bengaluru',
    'supreme_court_india':  'Supreme Court of India, New Delhi',
    'Karnataka Mediation Centre': 'Karnataka Mediation Centre',
}

COURT_TO_BUILDING = {
    'city_civil':           'city_civil_complex',
    'small_causes':         'city_civil_complex',
    'city_civil_rural':     'city_civil_complex',
    'dist_session_rural':   'city_civil_complex',
    'prl_senior_rural':     'city_civil_complex',
    'prl_junior_rural':     'city_civil_complex',
    'cmm':                  'magistrates_complex',
    'mmtc':                 'magistrates_complex',
    'mmtc_mayo':            'mayo_hall',
    'cjm_cmm_rural':        'magistrates_complex',
    'vacation_court_rural': 'magistrates_complex',
    'family':               'family_court',
    'consumer':               'consumer_court',
    'urban_consumer':         'cauvery_bhavan',
    'state_consumer_basava':  'state_consumer_basava',
    'dc_kandaya':             'kandaya_bhavan',
    'ac_kandaya':             'kandaya_bhavan',
    'mandya_district':        'mandya_district',
    'mandya_maddur':          'mandya_maddur',
    'mandya_malavalli':       'mandya_malavalli',
    'mandya_srirangapatna':   'mandya_srirangapatna',
    'mandya_nagamangala':     'mandya_nagamangala',
    'mandya_pandavapura':     'mandya_pandavapura',
    'mandya_krishnarajapet':  'mandya_krishnarajapet',
    'commercial':           'commercial_court',
    'commercial_court_rural': 'commercial_court',
    'mayo_hall':            'mayo_hall',
    'vacation_bench_family': 'family_court',
    'labour_court_rural':   'family_court',
    'labour_court_urban':   'family_court',
    'senior_anekal':        'anekal',
    'junior_anekal':        'anekal',
    'hosakote':             'hosakote',
    'devanahalli':          'devanahalli',
    'doddaballapur':        'doddaballapur',
    'nelamangala':          'nelamangala',
    'kr_puram':             'kr_puram',
    'high_court_karnataka': 'high_court',
    'supreme_court_india':  'supreme_court',
    'Karnataka Mediation Centre': 'mediation_centre',
}

BUILDING_LABELS = {
    'city_civil_complex': 'City Civil Court Complex',
    'magistrates_complex': 'Magistrate Court Complex',
    'family_court': 'Family Court Complex',
    'consumer_court':        'Consumer Court, Shantinagar',
    'cauvery_bhavan':        'Cauvery Bhavan',
    'state_consumer_basava': 'State Consumer, Basava Bhavan',
    'kandaya_bhavan':          'Kandaya Bhavan',
    'mandya_district':         'District Court Complex, Mandya',
    'mandya_maddur':           'Court Complex, Maddur',
    'mandya_malavalli':        'Court Complex, Malavalli',
    'mandya_srirangapatna':    'Court Complex, Srirangapatna',
    'mandya_nagamangala':      'Court Complex, Nagamangala',
    'mandya_pandavapura':      'Court Complex, Pandavapura',
    'mandya_krishnarajapet':   'Court Complex, Krishnarajapet',
    'commercial_court': 'Commercial Court Complex',
    'mayo_hall': 'Mayo Hall',
    'anekal': 'Anekal',
    'hosakote': 'Hosakote',
    'devanahalli': 'Devanahalli',
    'doddaballapur': 'Doddaballapur',
    'nelamangala': 'Nelamangala',
    'kr_puram': 'KR Puram',
    'high_court': 'High Court of Karnataka, Bengaluru',
    'supreme_court': 'Supreme Court of India, New Delhi',
    'mediation_centre': 'Karnataka Mediation Centre',
}

BUILDING_ORDER = [
    'city_civil_complex',
    'magistrates_complex',
    'family_court',
    'consumer_court',
    'cauvery_bhavan',
    'state_consumer_basava',
    'kandaya_bhavan',
    'commercial_court',
    'mayo_hall',
    'anekal',
    'hosakote',
    'devanahalli',
    'doddaballapur',
    'nelamangala',
    'kr_puram',
    'mandya_district',
    'mandya_maddur',
    'mandya_malavalli',
    'mandya_srirangapatna',
    'mandya_nagamangala',
    'mandya_pandavapura',
    'mandya_krishnarajapet',
    'high_court',
    'supreme_court',
    'mediation_centre',
]

# Valid court halls per court complex.
# Keyed by court code (same as COURT_LABELS keys), value is list of valid hall names.
# Used by the court hall notes system and cause list to tie hall + court together as one entity.
COURT_HALLS = {
    'cmm': [
        '14th Addl.', '36th ACJM', '52nd ACMM', 'IX ACMM', 'MMTC 4', 'MMTC 5',
        'XIII ACMM', 'XIV Addl. CMM', 'XIX ACJM', 'XIX ACMM', 'XLV ACMM',
        'XLVII ACMM', 'XLVIII ACMM', 'XX ACJM', 'XX ACMM', 'XXI ACMM',
        'XXX ACMM', 'XXXII ACMM', 'XXXIX ACJM', 'XXXIX ACMM', 'XXXVI ACJM',
        'XXXVI ACMM', 'XXXVII ACMM', 'xxx ADDL CJM', '52nd ACMM',
    ],
    'mmtc': ['MMTC 2', 'MMTC 3', 'MMTC 4', 'MMTC 5', 'MMTC 6', 'MMTC V'],
    'mmtc_mayo': ['MMTC 1'],
    'city_civil': [
        '43', 'CCH 1', 'CCH 14', 'CCH 15', 'CCH 16', 'CCH 19', 'CCH 2',
        'CCH 23', 'CCH 26', 'CCH 27', 'CCH 28', 'CCH 3', 'CCH 30', 'CCH 36',
        'CCH 42', 'CCH 43', 'CCH 5', 'CCH 54', 'CCH 57', 'CCH 59', 'CCH 6',
        'CCH 61', 'CCH 64', 'CCH 8', 'CCH 9', 'CCH-5', 'CCH-64',
        'II Addl. Senior', 'SCCH 7', 'SCCH 9', 'SCCH-2', 'city civil judge',
        '6th FC',
    ],
    'family': [
        '1st FC', '2nd Senior Civil Court', '3rd FC', '4th FC', '5th FC', '6th FC',
        'I Addl.', 'II Addl.', 'III Addl.', 'III PRL JUDGE', 'Prl. FC',
        'VI Addl FC', 'X Addl.', 'X FC', 'XI Addl.', 'XI FC',
    ],
    'small_causes': ['12', 'SCCH 2', 'SCCH 7', 'SCCH 8'],
    'mayo_hall': ['34th ACMM', 'XXXIII ACMM', 'XXXIV ACMM'],
    'commercial': ['CCH 1'],
    'consumer': ['II Addl.', 'III Addl.', 'IV Addl.'],
    'urban_consumer': ['II Addl.', 'Urban Consumer'],
    'state_consumer_basava': ['Prl bench 1', 'State Consumer'],
    'dc_kandaya': ['DC Court'],
    'ac_kandaya': ['AC Court'],
    'mandya_district': ['JMFC  Mandya', 'Main'],
    'mandya_maddur': ['Main'],
    'mandya_malavalli': ['Main'],
    'mandya_srirangapatna': ['Main'],
    'mandya_nagamangala': ['Main'],
    'mandya_pandavapura': ['Main'],
    'mandya_krishnarajapet': ['Main'],
    'city_civil_rural': ['1st Addl.CJM', '3rd Adll. senior', 'Prl. Civil'],
    'dist_session_rural': ['Main'],
    'prl_senior_rural': [
        '4th Addl.', 'I Addl.', 'II Addl.', 'Prl. Senior', 'VII Addl.', 'VIII', 'VIII Addl.',
    ],
    'prl_junior_rural': [
        '1', '3 addl civil judge', 'I Addl.', 'II Addl.', 'III Addl.', 'IV Addl.', 'Prl. Civil',
    ],
    'cjm_cmm_rural': ['CJM', 'CJM rural court', 'I Addl.'],
    'vacation_court_rural': ['Main'],
    'vacation_bench_family': ['Main'],
    'commercial_court_rural': ['Main'],
    'labour_court_rural': ['Main'],
    'labour_court_urban': ['Main'],
    'senior_anekal': ['Senior Civil judge and JMFC', 'Senior civil judge and JMFC'],
    'junior_anekal': ['III Addl.'],
    'hosakote': ['Main'],
    'devanahalli': ['Main'],
    'doddaballapur': ['Main'],
    'nelamangala': ['Main'],
    'kr_puram': ['Main'],
    'high_court_karnataka': ['Kalburgi', 'Main'],
    'supreme_court_india': ['Main'],
    'Karnataka Mediation Centre': ['Mediation', 'Main'],
}
