from django.urls import path
from .views import *
from .api import pending_messages, mark_sent

urlpatterns = [
    path('', home, name='home'),
    path('new_case/', new_case, name='new_case'),
    path('batch_new_case/', batch_new_case, name='batch_new_case'),
    path('diary_entry/', diary_entry, name='diary_entry'),
    path('diary_entry_case/<int:case_id>/', diary_entry_case, name='diary_entry_case'),
    path('diary_entry_case/<int:case_id>/create_execution_case/', create_execution_case, name='create_execution_case_from'),
    path('diary_entry_case/<int:case_id>/add_mediation_business/', add_mediation_business, name='add_mediation_business'),
    path('diary_entry_case/<int:case_id>/close_mediation/', close_mediation, name='close_mediation'),
    path('diary_entry_case/<int:case_id>/add_business/', add_business, name='add_business'),
    path('case/<int:case_id>/export/docx/', case_export_docx, name='case_export_docx'),
    path('case/<int:case_id>/export/pdf/', case_export_pdf, name='case_export_pdf'),
    path('diary_entry_case/<int:case_id>/refer_to_mediation/', refer_to_mediation, name='refer_to_mediation'),
    path('diary_entry_case/<int:case_id>/update_mediation_status/', update_mediation_status, name='update_mediation_status'),
    path('edit_business/<int:entry_id>/', edit_business, name='edit_business'),
    path('cause_list/', cause_list, name='cause_list'),
    path('cause_list/docx/', cause_list_docx, name='cause_list_docx'),
    path('cause_list/pdf/', cause_list_pdf, name='cause_list_pdf'),
    path('search/', case_search, name='search_cases'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('change_password/', change_password, name='change_password'),
    path('manage/', super_dashboard, name='super_dashboard'),
    path('manage/admins/create/', super_create_admin, name='super_create_admin'),
    path('manage/users/', manage_users, name='manage_users'),
    path('manage/users/create/', admin_create_user, name='admin_create_user'),
    path('manage/users/<int:user_id>/toggle/', toggle_user_active, name='toggle_user_active'),
    path('manage/users/<int:user_id>/reset_password/', admin_reset_password, name='admin_reset_password'),
    path('manage/users/<int:user_id>/', user_detail, name='user_detail'),
    path('manage/users/<int:user_id>/regenerate_telegram_code/', regenerate_telegram_code, name='regenerate_telegram_code'),
    path('telegram/webhook/', telegram_webhook, name='telegram_webhook'),
    path('court_halls/suggest/', suggest_court_halls, name='suggest_court_halls'),
    path('court_hall_notes/', court_hall_notes, name='court_hall_notes'),
    path('court_hall_notes/add/', add_court_hall_note, name='add_court_hall_note'),
    path('reminder/<int:reminder_id>/toggle/', mark_reminder_done, name='mark_reminder_done'),
    path('send_reminders_now/', send_reminders_now, name='send_reminders_now'),
    path('api/pending-messages/', pending_messages, name='api_pending_messages'),
    path('api/mark-sent/<int:msg_id>/', mark_sent, name='api_mark_sent'),
]
