# Generated by Django 5.2.15 on 2026-07-21 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0024_outmsg_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('applies_to', models.CharField(choices=[('both', 'Both'), ('petitioner', 'Petitioner'), ('respondent', 'Respondent')], default='both', max_length=20)),
                ('requires_cc_criminal', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CasePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_phone', models.CharField(blank=True, default='', max_length=20)),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_one_time', models.BooleanField(default=False)),
                ('one_time_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('appearance_included', models.BooleanField(default=False)),
                ('appearance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fully_paid', models.BooleanField(default=False)),
                ('fully_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='main.case')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_charges', to='payments.casepricing')),
            ],
        ),
        migrations.CreateModel(
            name='DiaryEntryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='main.diaryentry')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntryClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('auto_classified', models.BooleanField(default=True)),
                ('classified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='main.diaryentry')),
            ],
        ),
        migrations.CreateModel(
            name='EntryChargeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_charge_name', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charge_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.chargetype')),
                ('entry_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_items', to='payments.entryclassification')),
            ],
        ),
        migrations.CreateModel(
            name='OneTimeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('included_in_one_time', models.BooleanField(default=True)),
                ('per_occurrence_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_extras', to='payments.casepricing')),
            ],
        ),
        migrations.CreateModel(
            name='CaseChargeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('case_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_amounts', to='payments.casepricing')),
                ('charge_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.chargetype')),
            ],
            options={
                'unique_together': {('case_pricing', 'charge_type')},
            },
        ),
    ]
