# Generated by Django 5.2.15 on 2026-07-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_client_invoice_transaction_caseclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casepricing',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='casepricing',
            name='client_phone',
        ),
    ]
