# Generated by Django 5.2.15 on 2026-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_casepricing_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryclassification',
            name='invoice_message',
            field=models.TextField(blank=True, default='', help_text='Custom message for the invoice (overrides business text)'),
        ),
    ]
