# Generated by Django 5.2.15 on 2026-07-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_entryclassification_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
