# Generated by Django 6.0.6 on 2026-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(choices=[('urban', 'Bengaluru Urban'), ('rural', 'Bengaluru Rural')], max_length=20)),
                ('court_level', models.CharField(choices=[('district', 'District Court'), ('high_court', 'High Court of Karnataka'), ('supreme_court', 'Supreme Court of India')], max_length=20)),
                ('court', models.CharField(max_length=100)),
                ('court_hall', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('case_type', models.CharField(max_length=100)),
                ('case_number', models.CharField(max_length=100)),
                ('case_year', models.IntegerField()),
                ('party_1', models.CharField(max_length=100)),
                ('party_1_type', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('applicant', 'Applicant'), ('complainant', 'Complainant'), ('decree_holder', 'Decree Holder'), ('caveator', 'Caveator')], max_length=20)),
                ('party_2', models.CharField(max_length=100)),
                ('party_2_type', models.CharField(choices=[('defendant', 'Defendant'), ('respondent', 'Respondent(s)'), ('judgment_debtor', 'Judgment Debtor'), ('accused', 'Accused')], max_length=20)),
                ('representing', models.CharField(max_length=100)),
            ],
        ),
    ]
