# Generated by Django 6.0.6 on 2026-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.CharField(choices=[('urban', 'Bengaluru Urban'), ('rural', 'Bengaluru Rural')], default=None, max_length=20),
        ),
    ]
