# Generated by Django 5.2.15 on 2026-06-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_case_jurisdiction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='party_1_type',
            field=models.CharField(choices=[('petitioner', 'Petitioner'), ('plaintiff', 'Plaintiff'), ('applicant', 'Applicant'), ('complainant', 'Complainant'), ('decree_holder', 'Decree Holder'), ('caveator', 'Caveator')], max_length=20),
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField()),
                ('court', models.CharField(max_length=100)),
                ('court_hall', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('case_number_display', models.CharField(max_length=200)),
                ('representing', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=100)),
                ('business', models.TextField()),
                ('list_i', models.IntegerField(blank=True, null=True)),
                ('list_ii', models.IntegerField(blank=True, null=True)),
                ('next_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advocate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='main.case')),
            ],
            options={
                'ordering': ['-previous_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('advocate', 'Advocate'), ('intern', 'Intern')], default='intern', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
