# Generated by Django 5.2.15 on 2026-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_case_disposed_alter_case_party_1_type_diaryentry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='party_1_type',
            field=models.CharField(choices=[('Petitioner', 'Petitioner'), ('Plaintiff', 'Plaintiff'), ('Applicant', 'Applicant'), ('Complainant', 'Complainant'), ('Decree Holder', 'Decree Holder'), ('Caveator', 'Caveator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='party_2_type',
            field=models.CharField(choices=[('Defendant', 'Defendant'), ('Respondent(s)', 'Respondent(s)'), ('Judgment Debtor', 'Judgment Debtor'), ('Accused', 'Accused')], max_length=20),
        ),
    ]
