# Generated by Django 5.2.15 on 2026-06-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_case_party_1_type_alter_case_party_2_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='list_i',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='list_ii',
        ),
        migrations.CreateModel(
            name='CauseListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('list_i', models.IntegerField(blank=True, null=True)),
                ('list_ii', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_list_entries', to='main.case')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'case')},
            },
        ),
    ]
