# Generated by Django 5.2.15 on 2026-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_diaryentry_list_i_remove_diaryentry_list_ii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
