# Generated by Django 5.2.15 on 2026-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_userprofile_left_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='representing_parties',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='representing_parties',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='CourtHallNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.CharField(max_length=100)),
                ('court_hall', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Court Hall Note',
                'verbose_name_plural': 'Court Hall Notes',
                'unique_together': {('court', 'court_hall')},
            },
        ),
    ]
