# Generated by Django 5.2.15 on 2026-06-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_case_representing_parties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='party_1_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='case',
            name='party_2_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='party_1_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='party_2_total',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
