# Generated by Django 5.2.15 on 2026-06-25 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_case_party_1_total_case_party_2_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300)),
                ('start_on', models.DateField()),
                ('frequency', models.CharField(choices=[('daily', 'Every Day'), ('alternate', 'Alternate Days'), ('twice_week', 'Twice a Week'), ('weekly', 'Once a Week')], default='daily', max_length=20)),
                ('ramp_up', models.BooleanField(default=False, help_text='Increase frequency as next hearing date approaches')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='main.diaryentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
