# Generated by Django 5.2.15 on 2026-06-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
