# Generated by Django 5.2.15 on 2026-06-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_outgoingmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='mediation_next_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='mediation_status',
            field=models.CharField(choices=[('none', 'Not in Mediation'), ('referred', 'Referred to Mediation'), ('ongoing', 'Mediation Ongoing'), ('settled', 'Settled at Mediation'), ('failed', 'Mediation Failed')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='entry_type',
            field=models.CharField(choices=[('business', 'Court Business'), ('mediation', 'Mediation')], default='business', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='party_2_type',
            field=models.CharField(choices=[('Defendant', 'Defendant'), ('Respondent(s)', 'Respondent(s)'), ('Judgment Debtor', 'Judgment Debtor'), ('Accused', 'Accused'), ('Opposite Party/ies', 'Opposite Party/ies')], max_length=20),
        ),
    ]
