# Generated by Django 5.2.15 on 2026-06-29 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_case_mediation_next_date_case_mediation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='related_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_cases', to='main.case'),
        ),
    ]
