# Generated by Django 5.2.15 on 2026-06-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_case_related_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='mediation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
