# Generated by Django 5.2.15 on 2026-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_diaryentry_mediation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('update_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
