# Generated by Django 5.2.15 on 2026-07-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_telegram_update_dedup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtHallIncharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('court', models.CharField(max_length=100)),
                ('court_hall', models.CharField(max_length=100)),
                ('is_incharge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Court Hall Incharge',
                'verbose_name_plural': 'Court Hall Inchargs',
                'unique_together': {('date', 'court', 'court_hall')},
            },
        ),
    ]
