# Generated by Django 5.2.15 on 2026-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_courthallincharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cnr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='business_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='ecourts_business',
            field=models.TextField(blank=True, default=''),
        ),
    ]
