# Generated by Django 5.2.15 on 2026-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_ecourts_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ecourts_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ecourts_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
