# Generated by Django 5.2.15 on 2026-07-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='party_1_type',
            field=models.CharField(choices=[('Petitioner', 'Petitioner'), ('Plaintiff', 'Plaintiff'), ('Applicant', 'Applicant'), ('Complainant', 'Complainant'), ('Decree Holder', 'Decree Holder'), ('Caveator', 'Caveator'), ('Appellant', 'Appellant')], max_length=20),
        ),
    ]
