# Generated by Django 5.2.15 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_case_party_1_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='jurisdiction',
            field=models.CharField(choices=[('urban', 'Bengaluru Urban'), ('rural', 'Bengaluru Rural'), ('mandya', 'Mandya')], default=None, max_length=20),
        ),
    ]
