# Generated by Django 5.2.15 on 2026-07-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_case_jurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_ecourts',
            field=models.BooleanField(default=False),
        ),
    ]
