# Generated by Django 5.2.15 on 2026-07-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_userprofile_can_access_ecourts'),
    ]

    operations = [
        migrations.AddField(
            model_name='courthallnote',
            name='default_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
