# Generated by Django 5.2.15 on 2026-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_court_hall_note_default_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='sent',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='outgoingmessage',
            index=models.Index(fields=['sent', 'created_at'], name='idx_outmsg_sent_created'),
        ),
    ]
