# Generated by Django 5.2.15 on 2026-07-24 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_outmsg_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diaryentry',
            index=models.Index(fields=['case', 'previous_date', 'entry_type'], name='main_diarye_case_id_c05f6c_idx'),
        ),
    ]
