# Generated by Django 5.2.15 on 2026-07-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_diaryentry_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='causelistentry',
            name='mediation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
