# Generated by Django 5.2.15 on 2026-07-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_causelistentry_mediation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='courthallincharge',
            name='incharge_court_hall',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
